[project]
name = "yys"
version = "1.0.0"
description = "yys"
authors = [
    { name = "shaoyangzi", email = "shaoyangz1@163.com" },
]
dependencies = [
    "airtest>=1.2.7",
    "loguru>=0.6.0",
    "black>=22.12.0",
    "pydantic[dotenv]>=1.10.3",
]
requires-python = ">=3.9,<3.10"
license = { text = "MIT" }

[tool.pdm]
[tool.pdm.scripts]
yys = "python main.py"
