[project]
name = ""
version = ""
description = ""
authors = [
    {name = "shaoyangzi", email = "shaoyangzi@xd.com"},
]
dependencies = [
    "airtest>=1.2.7",
    "pydantic[dotenv]>=1.10.2",
    "loguru>=0.6.0",
    "black>=22.10.0",
]
requires-python = ">=3.9"
license = {text = "MIT"}

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"

[tool.pdm]
[tool.pdm.scripts]
yys = "python main.py"